# fly.toml app configuration file generated for akluma-prod on 2025-03-26T09:23:50Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'akluma-staging'
primary_region = 'cdg'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'staging'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = ""
  cron = "cron -f"
  worker = "php artisan queue:work --tries=3 --max-time=3600"

[processes.worker]
  auto_stop_machines = false
  min_machines_running = 1
